# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- prod

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo $(Build.SourcesDirectory) is the working dir. Files:
    ls -al $(Build.SourcesDirectory)

  displayName: 'List working dir'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true
    architecture: 'x64'

- script: |
    echo Installing requirements...
    make
    make dependencies

- script: |
    echo Running tests:
    chmod 700 tests.sh
    ./tests.sh

  displayName: 'Run tests'
